### ISSUE TITLE
PackageVersion API is reporting build & revision as 65535 on Android

### ISSUE THREAD

**Issue by jamesmcroft** [XPlat-Apps/XPlat-Windows-APIs#51]
Missed during testing, the Android PackageVersion is reporting a value of 1.0.65535.65535 on a new Android application created from Visual Studio. 

Believe this is to do with the value that is returned from the VersionName property of the Android PackageInfo which only reports the Major and Minor number.

**Comment by peterfoot** [comment]
This is because a parsed Version sets any unspecified elements to -1 which converts to ushort.MaxValue when converted to a PackageVersion. I worked around this by only setting build and revision if these elements have a value - ignoring any -1 values - https://github.com/inthehand/Pontoon/blob/master/Source/InTheHand/ApplicationModel/PackageVersionExtensions.cs

Hope that helps!

**Comment by jamesmcroft** [comment]
@peterfoot thanks for the tip! Android versioning is a little odd, we've been looking into this at work, in particular, automating versioning with Azure DevOps, and noticed that it doesn't work like other platforms, especially when it comes to in-place upgrade with newer versions.

**Comment by tom-made** [comment]
@jamesmcroft are we looking to release this as a hot fix to the current release?

**Comment by jamesmcroft** [comment]
@tom-made yes. I'll have to manually queue the build and deploy. Can sort that out this evening.
